### ISSUE TITLE
你的七牛 token 暴露了。。

### ISSUE THREAD

**Issue by EkkoG** [Narcissist1/hexo_engine#1]
看到的人拿到 token 就上传文件了。。甚至直接用你的空间- -

**Comment by Yucheng-Ren** [comment]
忘记ignore了。。。。

**Comment by EkkoG** [comment]
也没办法 ignore 吧。。ignore 了config 文件这个项目就不完整了。。

-- 
Kevin Guo
Sent with Airmail

在 2016年4月4日 下午10:21:19, Ren Yucheng (notifications@github.com) 写到:

忘记ignore了。。。。

**Comment by Yucheng-Ren** [comment]
那也没办法了，这个应该不支持从其他文件引入吧，像 python 那样

**Comment by EkkoG** [comment]
你把这个工程放出来是想做什么用？

-- 
Kevin Guo
Sent with Airmail

在 2016年4月4日 下午10:26:46, Ren Yucheng (notifications@github.com) 写到:

那也没办法了，这个应该不支持从其他文件引入吧，像 python 那样

**Comment by Yucheng-Ren** [comment]
没什么用啊，做个备份而已。万一哪天电脑坏掉也不至于找不到

**Comment by EkkoG** [comment]
那不用放 Github 的，放 coding 上就可以的，或者打包放 Dropbox？

-- 
Kevin Guo
Sent with Airmail

在 2016年4月4日 下午10:30:15, Ren Yucheng (notifications@github.com) 写到:

没什么用啊，做个备份而已。万一哪天电脑坏掉也不至于找不到

**Comment by EkkoG** [comment]
或者 bitbucket 也可以的，单纯的备份的话可以有好多选择

-- 
Kevin Guo
Sent with Airmail

在 2016年4月4日 下午10:30:15, Ren Yucheng (notifications@github.com) 写到:

没什么用啊，做个备份而已。万一哪天电脑坏掉也不至于找不到

**Comment by Yucheng-Ren** [comment]
嗯，习惯了，最近在试着用 gitlab， 有空迁移过去

**Comment by EkkoG** [comment]
哈哈好吧，就是提个醒，祝生活愉快。

-- 
Kevin Guo
Sent with Airmail

在 2016年4月4日 下午10:34:57, Ren Yucheng (notifications@github.com) 写到:

嗯，习惯了，最近在试着用 gitlab， 有空迁移过去

**Comment by Yucheng-Ren** [comment]
多谢:)
